# Generated by Django 5.0.3 on 2024-07-12 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form_en", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="form_enquiry",
            new_name="form_enquirys",
        ),
    ]
